[workspace]

[package]
name = "helloworld"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wee_alloc = { version = "0.4.5", optional = true }

[features]
default = ["wee_alloc"]

[profile.release]
opt-level = 's'
lto = true
strip = true
