[package]
name = "wasm-host"
version = "0.0.1"
edition = "2021"

[dependencies]
wasmedge-sdk = { version = "0.14.0", features = ["standalone", "static"] }
serde_json = "1.0.135"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }